/**
 * PM2 ecosystem for production deployment.
 *
 * Usage on VPS:
 *   pm2 start ecosystem.config.cjs --env production
 *   pm2 save
 *   pm2 startup        # auto-start on reboot
 *   pm2 reload cuulongmytuu   # zero-downtime reload after deploy
 *
 * Run with: `node server.js` from the .next/standalone bundle.
 * Build with: `npm run build` then copy .next/standalone, .next/static, public.
 */

module.exports = {
  apps: [
    {
      name: "cuulongmytuu",
      // Standalone server entry generated by `output: 'standalone'`.
      script: ".next/standalone/server.js",
      cwd: __dirname,
      // 1 process per CPU core; cluster mode load-balances over the same port.
      instances: "max",
      exec_mode: "cluster",
      // Restart if a worker leaks past 512MB.
      max_memory_restart: "512M",
      // Don't go into a crash loop — back off after 5 unstable restarts in 60s.
      min_uptime: "60s",
      max_restarts: 5,
      // Wait this long for graceful shutdown before SIGKILL.
      kill_timeout: 5000,
      listen_timeout: 10000,
      // Logs (rotated by pm2-logrotate; install with `pm2 install pm2-logrotate`).
      out_file: "./logs/out.log",
      error_file: "./logs/err.log",
      merge_logs: true,
      time: true,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        // Trust proxy headers from Nginx so rate-limit reads the real client IP.
        // (Next.js reads X-Forwarded-For automatically; this is documented intent.)
      },
    },
  ],
};
